server:
  port: 8081

spring:
  application:
    name: dubbo-provider
  profiles:
    active: dev

custom:
  name: wenky
  age: 26

# springboot actuator 监控
management:
  endpoints:
    web:
      exposure:
        include: '*'

app:
  config:
    log:
      level: info
      path: /Users/huwenqi/Documents/wenky/java/ddd-web/ddd-web-dubbo-provider

dubbo:
  application:
    name: dubbo-provider
    logger: slf4j
  protocol:
    port: 20880
    name: dubbo
  registry:
    address: nacos://localhost:8848
  scan:
    base-packages: com.wenky.ddd.provider.dubbo.service.impl