server:
  port: 8081

spring:
  application:
    name: dubbo-provider
  profiles:
    active: dev
  datasource:
    # DataSourceConfiguration#Hikari=>dataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/dubbo_provider?useSSL=false&useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=true
    username: root
    password: root
    hikari:
      pool-name: dubbo-provider-db-pool
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      read-only: false
      connection-test-query: select 1
      data-source-properties:
  jpa:
    database: mysql
    # 设置数据库方言
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      temp.use_jdbc_metadata_defaults: false

custom:
  name: wenky
  age: 26

# springboot actuator 监控
management:
  endpoints:
    web:
      exposure:
        include: '*'

app:
  config:
    log:
      level: INFO
      path: /Users/huwenqi/Documents/wenky/java/ddd-web/ddd-web-dubbo-provider

dubbo:
  application:
    name: dubbo-provider
  config-center:
    namespace: 7c9923ad-98f2-4a24-a5c3-4840633a64c5
    logger: slf4j
  protocol:
    port: 20880
    name: dubbo
  registry:
    address: nacos://localhost:8848
  scan:
    base-packages: com.wenky.ddd.provider.dubbo.service.impl